BEGIN;

-- ================================
-- Create model: User
-- ================================
CREATE TABLE inventory_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL
);

-- ================================
-- Create model: Order
-- ================================
CREATE TABLE inventory_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL REFERENCES inventory_user(id) DEFERRABLE INITIALLY DEFERRED
);

-- ================================
-- Create model: PromotionEvent
-- ================================
CREATE TABLE inventory_promotionevent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    price_reduction INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL
);

-- ================================
-- Create model: Category
-- ================================
CREATE TABLE inventory_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    slug VARCHAR(55) NOT NULL UNIQUE,
    level SMALLINT NOT NULL,
    is_active BOOLEAN NOT NULL,
    parent_id BIGINT NULL REFERENCES inventory_category(id) DEFERRABLE INITIALLY DEFERRED
);

-- ================================
-- Create model: Product
-- ================================
CREATE TABLE inventory_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    slug VARCHAR(55) NOT NULL UNIQUE,
    description TEXT NULL,
    is_digital BOOLEAN NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    price NUMERIC NOT NULL,
    category_id BIGINT NOT NULL REFERENCES inventory_category(id) DEFERRABLE INITIALLY DEFERRED
);

-- ================================
-- Create model: OrderProduct (Many-to-Many)
-- ================================
CREATE TABLE inventory_orderproduct (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL,
    order_id BIGINT NOT NULL REFERENCES inventory_order(id) DEFERRABLE INITIALLY DEFERRED,
    product_id BIGINT NOT NULL REFERENCES inventory_product(id) DEFERRABLE INITIALLY DEFERRED
);

-- ================================
-- Create model: StockManagement
-- ================================
CREATE TABLE inventory_stockmanagement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL,
    last_checked_at TIMESTAMP NOT NULL,
    product_id BIGINT NOT NULL UNIQUE REFERENCES inventory_product(id) DEFERRABLE INITIALLY DEFERRED
);

-- ================================
-- Create model: ProductPromotionEvent (Join Table)
-- ================================
CREATE TABLE inventory_productpromotionevent (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES inventory_product(id) DEFERRABLE INITIALLY DEFERRED,
    promotion_event_id BIGINT NOT NULL REFERENCES inventory_promotionevent(id) DEFERRABLE INITIALLY DEFERRED
);

COMMIT;
